### PR TITLE
🐛 remove the +required marker for backend

### LINKED ISSUE #586: bug: adoption creates invalid ControlPlane object
### Describe the bug

https://github.com/kubestellar/kubeflex/blob/fb35e66a6bba6f27ac9a462909ee4510feaf8743/api/v1alpha1/controlplane_types.go#L29 says that `.spec.backend` is required. The type of this field is an enumerated type with just two valid values: "shared" and "dedicated". In Go there is no such thing as a struct with one of its defined fields absent; the only question is whether the field's value is its type's zero value or not.

https://github.com/kubestellar/kubeflex/blob/fb35e66a6bba6f27ac9a462909ee4510feaf8743/cmd/kflex/adopt/adopt.go#L128 creates a ControlPlane whose `.Spec.Backend` is the empty string.

### Steps To Reproduce

In `test/e2e/run.sh`, interrupt it while `manage-type-external.sh` has the external ControlPlane in existence; see that it does indeed break the requirement that `.spec.backend` exists (i.e., is not the empty string).

```console
mspreitz@mjs13 kubeflex % kubectl --context kind-kubeflex get cps ext -o yaml
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: ControlPlane
metadata:
  creationTimestamp: "2025-12-11T06:15:44Z"
  finalizers:
  - kflex.kubestellar.org/finalizer
  generation: 1
  name: ext
  resourceVersion: "2323"
  uid: 768e63cc-b590-4f94-a6b8-b190edd53fda
spec:
  bootstrapSecretRef:
    inClusterKey: kubeconfig-incluster
    name: ext-bootstrap
    namespace: kubeflex-system
  postCreateHook: list-controller
  tokenExpirationSeconds: 31536000
  type: external
  waitForPostCreateHooks: false
status:
  conditions:
  - lastTransitionTime: "2025-12-11T06:15:44Z"
    lastUpdateTime: "2025-12-11T06:15:44Z"
    message: ""
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2025-12-11T06:15:44Z"
    lastUpdateTime: "2025-12-11T06:15:44Z"
    message: ""
    reason: Available
    status: "True"
    type: Ready
  observedGeneration: 1
  postCreateHookCompleted: true
  postCreateHooks:
    list-controller: true
  secretRef:
    inClusterKey: kubeconfig-incluster
    key: kubeconfig
    name: admin-kubeconfig
    namespace: ext-system
```

### Expected Behavior

The code is self-consistent.

### Additional Context

This inconsistency was discovered in CI of #583 . Why was this not discovered earlier?

### PR DESCRIPTION
**Pull request by pdettori**
## Summary

relax the "required" condition to make .spec.backend optional.

## Related issue(s)

Fixes #586

### CODE REVIEW

File: api/v1alpha1/controlplane_types.go [hunk 1]
```diff
@@ -26,7 +26,10 @@ type ControlPlaneSpec struct {
 	// +required
 	Type ControlPlaneType `json:"type,omitempty"`
 	// backend refers to the database type used by the control plane
```
Comment (MikeSpreitzer) [inline api/v1alpha1/controlplane_types.go]: Need a period at the end of this sentence.

File: api/v1alpha1/controlplane_types.go [hunk 2]
```diff
@@ -26,7 +26,10 @@ type ControlPlaneSpec struct {
...
-	// +required
+	// For external control planes this field is optional; controller
+	// logic can ignore it for `external` type instances. Removed
```
Comment (MikeSpreitzer) [inline api/v1alpha1/controlplane_types.go]: If I understand correctly, the following would be a simpler clearer statement.

> For external control planes this field is irrelevant and may be omitted (I.e., contain the empty string).

**Review by MikeSpreitzer — APPROVED** [review]
This is good enough to merge.
/lgtm
/approve
